<Project>
  <!-- Module packages versions. -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Define paths of the Hexalith packages props. -->
    <Hexalith1BuildPackageProps>$(MSBuildThisFileDirectory)references/Hexalith.Builds/Props/Directory.Packages.props</Hexalith1BuildPackageProps>
    <Hexalith2BuildPackageProps>$(MSBuildThisFileDirectory)../Hexalith.Builds/Props/Directory.Packages.props</Hexalith2BuildPackageProps>
    <Hexalith3BuildPackageProps>$(MSBuildThisFileDirectory)../../Hexalith.Builds/Props/Directory.Packages.props</Hexalith3BuildPackageProps>
  </PropertyGroup>
  <!-- Import the required Hexalith.Packages.props file. -->
  <Import Project="$(Hexalith1BuildPackageProps)" Condition="Exists('$(Hexalith1BuildPackageProps)') And '$(HexalithVersionsLoaded)' != 'true'" />
  <Import Project="$(Hexalith2BuildPackageProps)" Condition="Exists('$(Hexalith2BuildPackageProps)') And '$(HexalithVersionsLoaded)' != 'true'" />
  <Import Project="$(Hexalith3BuildPackageProps)" Condition="'$(HexalithVersionsLoaded)' != 'true'" />
  <ItemGroup>
    <!-- Define packages versions for this module. -->
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.Abstractions" Version="10.0.9" />
    <PackageVersion Update="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
    <PackageVersion Update="Microsoft.Extensions.ServiceDiscovery" Version="10.7.0" />
    <PackageVersion Update="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
    <PackageVersion Update="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
    <PackageVersion Update="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
    <PackageVersion Update="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
    <PackageVersion Update="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageVersion Update="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.4.0-preview.1.260602-0230" />
    <PackageVersion Update="ByteAether.Ulid" Version="1.3.7" />
    <PackageVersion Include="MinVer" Version="8.0.0-rc.1" />
  </ItemGroup>
</Project>
