name: Build Packages
on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: read
     
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - name: Initialize .NET
      uses: Hexalith/Hexalith.Builds/Github/initialize-dotnet@main

    - name: Initialize Build
      uses: Hexalith/Hexalith.Builds/Github/initialize-build@main

    - name: Get Version
      id: version
      uses: Hexalith/Hexalith.Builds/Github/version@main
      with:
        ref: ${{ github.ref}}
        buildId: ${{ github.run_number }}
        buildAttempt: ${{ github.run_attempt }}
        
    - name: Run Unit Tests of version (${{ steps.version.outputs.version }})
      uses: Hexalith/Hexalith.Builds/Github/unit-tests@main
      with:
        project-name: ${{ github.event.repository.name }}

    - name: Build Packages version (${{ steps.version.outputs.version }})
      uses: Hexalith/Hexalith.Builds/Github/build-packages@main
      with:
        version: ${{ steps.version.outputs.version }}
        
    - name: Publish Packages
      uses: Hexalith/Hexalith.Builds/Github/publish-packages@main
      with:
        version: ${{ steps.version.outputs.version }}
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}


    
