name: Build Packages
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: 
      - main
      - release-*
    tags:
      - 'v*'
  pull_request:
    branches: 
      - master
      - release-*
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Staging 
    name: Build, Test, Publish (${{ github.ref_name }})
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Initialize .NET
      uses: Hexalith/Hexalith.Builds/Github/initialize-dotnet@main
    - name: Initialize Build
      uses: Hexalith/Hexalith.Builds/Github/initialize-build@main
    - name: Get Version
      id: version
      uses: Hexalith/Hexalith.Builds/Github/version@main
      with:
        preview: ${{ !startsWith(github.ref, 'refs/tags/') && 'preview' || '' }}
        buildId: ${{ github.run_number }}
        buildAttempt: ${{ github.run_attempt }}
    - name: Run Unit Tests
      uses: Hexalith/Hexalith.Builds/Github/unit-tests@main
      with:
        project-name: ${{ github.event.repository.name }}

    