<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);IDE0079;RCS1251;CA2201;VSTHRD111;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\libraries\Hexalith.Commons.Configurations\Hexalith.Commons.Configurations.csproj" />
    <ProjectReference Include="..\..\src\libraries\Hexalith.Commons.Metadatas\Hexalith.Commons.Metadatas.csproj" />
    <ProjectReference Include="..\..\src\libraries\Hexalith.Commons.StringEncoders\Hexalith.Commons.StringEncoders.csproj" />
    <ProjectReference Include="..\..\src\libraries\Hexalith.Commons.UniqueIds\Hexalith.Commons.UniqueIds.csproj" />
    <ProjectReference Include="..\..\src\libraries\Hexalith.Commons\Hexalith.Commons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>